org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Signing configuration for release builds
MY_KEYSTORE_PASSWORD=H-Gmlt-2288
MY_KEY_ALIAS=my-key-alias
MY_KEY_PASSWORD=H-Gmlt-2288
storeFile=/Users/mohammadjrab/Documents/Projects/Syiran Pounds/android/app/my-release-key.jks
